### ISSUE TITLE
Getting Errors on running installation script in Ubuntu 23.10

### ISSUE THREAD

**Issue by vihaan-that** [BerqiaMouad/Neovim-Setup#1]
git clone https://github.com/BerqiaMouad/Neovim-Setup.git ~/.config/nvim
Cloning into '/home/user/.config/nvim'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 71 (delta 25), reused 60 (delta 14), pack-reused 0
Receiving objects: 100% (71/71), 4.88 MiB | 210.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.
(base) user/PC/:~$ cd ~/.config/nvim/mouad_codeforces_tool
pip install -r requirements.txt
Collecting termcolor==1.1.0 (from -r requirements.txt (line 1))
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.26.0 (from -r requirements.txt (line 2))
  Downloading requests-2.26.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting beautifulsoup4==4.10.0 (from -r requirements.txt (line 3))
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl.metadata (3.5 kB)
Collecting robobrowser==0.5.3 (from -r requirements.txt (line 4))
  Downloading robobrowser-0.5.3.tar.gz (22 kB)
  Preparing metadata (setup.py) ... done
Collecting Werkzeug==0.16.1 (from -r requirements.txt (line 5))
  Downloading Werkzeug-0.16.1-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting cached_property (from -r requirements.txt (line 6))
  Downloading cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting CodeforcesApiPy (from -r requirements.txt (line 8))
  Downloading CodeforcesApiPy-2.0.11.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement python3.10-venv (from versions: none)
ERROR: No matching distribution found for python3.10-venv

**Comment by BerqiaMouad** [comment]
Thank you for the heads up, I messed up the ordering of the dependencies to install, "python3.10-venv" needs to be before CodeforcesApiPy, it's successfully switched now!
